### ISSUE TITLE
7-BentoML

### ISSUE THREAD

**Issue by K0nkere** [K0nkere/ml-bookcamp#1]
Saving existing model
`bentoml.xgboost.save_model("credit-risk-model", model)` > Model(tag="credit-risk-model:z64yclsysod73467", path="/homw/winx/bentoml/models/credit-risk-model/z64yclsysod73467/")
We`ve got **tag** and **path**

**Comment by K0nkere** [comment]
Running the service
By default port 3000 is used

bentoml serve service.py:svc
bentoml serve <script_file.py : application>

**Comment by K0nkere** [comment]
CLI tools
`bentoml models list` - list of models
>
 credit-risk-model:dt3dblsytgd73467  bentoml.xgboost  196.44 KiB  2022-10-30 21:23:35 
 credit-risk-model:z64yclsysod73467  bentoml.xgboost  195.74 KiB  2022-10-30 20:45:38

**Comment by K0nkere** [comment]
#### Deployment via .yaml file
In the folder containing script-file.py
**bentofile.yaml**
```
service: "service.py:svc"  # Same as the argument passed to `bentoml serve`
labels:
    owner: kkr-ml-bookcamp
    stage: dev
include:
- "*.py"  # A pattern for matching which files to include in the bento
python:
    packages:  # Additional pip packages required by the service
    - scikit-learn
    - xgboost
```
