### ISSUE TITLE
Tensorflow Serving

### ISSUE THREAD

**Issue by K0nkere** [K0nkere/ml-bookcamp#7]
[Video](https://www.youtube.com/watch?v=deXR2fThYDw&list=PL3MmuxUbc_hIhxl5Ji8t4O6lPAOpHaCLR&index=100)
Need to save a model in special format for TF-serving
```
import tensorflow as tf
from tensorflow.keras.models import load_model

model = load_model("./xception_v4_large_08_0.894.h5")
tf.saved_model.save(model, "clothing-model")
```

**Comment by K0nkere** [comment]
In order to send a request to this model via gRPC its need to use PROTOBUFF
```
pip install grpcio==1.42.0 tensorflow-serving-api==2.7.0
pip install keras-image-helper
```

**Comment by K0nkere** [comment]
final gateway script

**Comment by K0nkere** [comment]
test script

**Comment by K0nkere** [comment]
adding pipenv dependencies

**Comment by K0nkere** [comment]
#### Dockerfile for image-gateway
```
FROM python:3.9.12-slim

WORKDIR /app
COPY ["gateway.py", "proto.py", "Pipfile", "Pipfile.lock", "./"]

RUN pip install -U pip
RUN pip install pipenv

RUN pipenv install --system --deploy

EXPOSE 9696

ENTRYPOINT [ "gunicorn", "--bind=0.0.0.0:9696", "gateway:app" ]
```
building
`docker build -t image-gateway:v01 -f image-gateway.dockerfile .`

**Comment by K0nkere** [comment]
### Docker-compose for 2 services
We are combining two services and we need  for gateway service can reach clothing-model service. It is possible to do so by adding environment variable that holds url of clothin-model service
And its need to fix gateway.py with
```
# host = "localhost:8500"
host = os.getenv("TF_SERVING_HOST", "localhost:8500")
```
Final **docker-compose.yaml** file
```
version: '3.7'
services:
  clothing-model:
    image: zoomcamp-10-model:v01
  gateway:
    image: zoomcamp-10-gateway:v01
    ports:
      - 9696:9696
    environment:
      - TF_SERVING_HOST=clothing-model:8500
```
