### ISSUE TITLE
10b-Kubernetes

### ISSUE THREAD

**Issue by K0nkere** [K0nkere/ml-bookcamp#8]
.

**Comment by K0nkere** [comment]
### Setting up a local Kubernetes cluster with **kind**

**Comment by K0nkere** [comment]
### Creating Kibernetes cluster with kind
`kind create cluster`

**Comment by K0nkere** [comment]
Its need to create few .yaml files so better to use VSCode extention Extentions > kubernetes from Microsoft

For deployment we need to specify how the pods will look like and then we will start the service

**Comment by K0nkere** [comment]
### Applying the deployment
`kubectl apply -f deployment.yaml` > `deployment.apps/ping-deployment created`

**Comment by K0nkere** [comment]
### Testing pod deployment without service creation

**Comment by K0nkere** [comment]
### TF-serving model + Gateway deployment
**model-deployment.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-clothing-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-clothing-model
  template:
    metadata:
      labels:
        app: tf-serving-clothing-model
    spec:
      containers:
      - name: tf-serving-clothing-model
        image: zoomcamp-10-model:v01
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8500
```
`kind load docker-image zoomcamp-10-model:v01`
`kubectl apply -f model-deployment.yaml`

**Comment by K0nkere** [comment]
### Gateway deployment
**model-service.yaml**

**Comment by K0nkere** [comment]
### Gateway model deployment
**gateway-deployment.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-model
spec:
  selector:
    matchLabels:
      app: gateway-model
  template:
    metadata:
      labels:
        app: gateway-model
    spec:
      containers:
      - name: gateway-model
        image: zoomcamp-10-gateway:v01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9696
```
`kind load docker-image zoomcamp-10-gateway:v01`
`kubectl apply -f gateway-deployment.yaml`

**Comment by K0nkere** [comment]
### Using telnet to make a request
From **ping-deployment** pod login with exec
`curl tf-serving-clothing-model.default.svc.cluster.local:8500` > result
> curl: (1) Received HTTP/0.9 when not allowed

**Comment by K0nkere** [comment]
Now apply gateway-deployment
`kubectl apply -f gateway-deployment.yaml`
`kubectl get pod`
```
NAME                                         READY   STATUS    RESTARTS   AGE
gateway-model-5c567cf5ff-qf8zl               1/1     Running   0          34s
ping-deployment-7459f4b7c7-csrpw             1/1     Running   0          18m
tf-serving-clothing-model-6dd675c99c-4g2lx   1/1     Running   0          76m
```

**Comment by K0nkere** [comment]
### Creating service for gateway-deployment
```
apiVersion: v1
kind: Service
metadata:
  name: gateway-model
spec:
  selector:
    app: gateway-model
  ports:
  - port: 80
    targetPort: 9696
```
`kubectl apply -f gateway-service.yaml`
